// app/_constants
export const banksList = [
  { value: "access", label: "Access Bank" },
  { value: "alternative", label: "The Alternative Bank" },
  { value: "ecobank", label: "Ecobank" },  
  { value: "fcmb", label: "FCMB" },
  { value: "fidelity", label: "Fidelity Bank" },
  { value: "first_bank", label: "First Bank" },
  { value: "gtb", label: "GT Bank" },
  { value: "globus", label: "Globus Bank" },
  { value: "jaiz", label: "JAIZ Bank" },
  { value: "kuda", label: "Kuda MFB" },
  { value: "lotus", label: "Lotus Bank" },
  { value: "moniepoint", label: "Moniepoint MFB" },
  { value: "myBankStatement", label: "Custom (My-Bank-Statement)" },
  { value: "nomba", label: "Nomba Bank" },
  { value: "opay", label: "Opay MFB" },
  // { value: "palmpay", label: "Palmpay MFB" },
  { value: "polaris", label: "Polaris Bank" },
  { value: "providus", label: "Providus Bank" },
  { value: "stanbic", label: "Stanbic IBTC Bank" },
  { value: "sterling", label: "Sterling Bank" },
  { value: "uba", label: "UBA" },
  { value: "union", label: "Union Bank" },
  { value: "wema", label: "WEMA Bank" },
  { value: "zenith", label: "Zenith Bank" },
];
